### ISSUE TITLE
Not import in live site

### ISSUE THREAD

**Issue by Naguchennai** [iazami/IMDBi#1]
Its work fine in my localhost after upload in live site it not import details???

**Comment by itshaadi** [comment]
what's your wordpress version?
More details please...
@naguchennai

**Comment by Naguchennai** [comment]
WordPress 4.3.3 .. indb search work, after click title it not show any just show ← Back symbol.. not whow any details.. its work all same wordpress vertion its work fine

**Comment by itshaadi** [comment]
It seems that crawler can't crawl in and extract some of items (budget - gross - trailer).
I wonder if crawler works fine in Localhost, then It must work as well in live site.
i will work on that.
@naguchennai

**Comment by Naguchennai** [comment]
Sorry this is server problem .. We must enable allow_url_fopen in server .. now it work fine in live site
