### ISSUE TITLE
Loading forever.

### ISSUE THREAD

**Issue by meugamer** [iazami/IMDBi#13]
Hello, how are you? I have the key key. But it's still on the loading page forever. Or just by the name of the movie comes back no return. How to solve?

**Comment by itshaadi** [comment]
similar to #11 #10 

> OMDBAPI went to private. so this project is currently useless until further notice, sorry.

**Comment by meugamer** [comment]
Hi, I know he's private. But I'm paying for the license key and I have api of them. That they provided me and I even modified in php the key. But still the loading is still going on. Would there be any other file that I should modify?
