### ISSUE TITLE
Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0

### ISSUE THREAD

**Issue by budmc29** [iazami/IMDBi#2]
The function is not supported by the compiled php for the host I am using and unfortunately I do not have access to any php configuration.

Is there any way to make the plugin work using a different function to get the data from IMDB?

**Comment by itshaadi** [comment]
Your server admin has disabled this functionality. You need to ask them to enable "allow_url_fopen" in php.ini.
But if cURL is available, using cURL is the best option for you.
@budmc29

**Comment by budmc29** [comment]
I implemented the functionality using curl. 
Maybe you can do a check to fall back to curs for users that don't have the option available, or I can work on something and do a pull request.

**Comment by itshaadi** [comment]
yeah feel free and send a pull request :)
@budmc29
