### ISSUE TITLE
Access denied for trailer

### ISSUE THREAD

**Issue by budmc29** [iazami/IMDBi#4]
When trying to get the trailer for a movie I get "Access denied".

Here is the link generated by the plugin: [trailer](http://video-http.media-imdb.com/MV5BMTQwMjI0MDQ4Nl5BMTFeQW1wNF5BbWU3MDQxMzAzMzM@.mp4?Expires=1459502713&Signature=ctuvrqWNePGZSaKl2z4QOrosQNYeDvjZTRQp~MlpChrnKaZbd3YISoGN8vpBqi8MypWM65xvsW4PcVO6t9dLtJoiZvcCGEWSiYtbo3WGZofoJN47gJZOxjM7-jorGdXk~WyxCUEx2dECGHQ9BtPEJoI8FEf50n5O7-w47R8vm5w_&Key-Pair-Id=APKAILW5I44IHKUN2DYA)

Am I missing something?

**Comment by itshaadi** [comment]
i'm working on a new update which will fix this issues, by using TMDB API
