### ISSUE TITLE
Traduccion al español , Translation to Spanish

### ISSUE THREAD

**Issue by zkmark** [iazami/IMDBi#5]
Here the translation into Spanish
Includes translation into Spanish from Spain and Mexico
Based on the fa_IR translation
---
Aqui la traduccion al español
incluye traduccion al español de españa y de mexico
basado en la traduccion fa_IR

https://mega.nz/#!LkhgmQia!5NBYmqBOJ0OLQtw22uL4YJguH5642Qt_ifFnmzirllg

**Comment by itshaadi** [comment]
Thanks a bunch, I appreciate your work.
In the next update, i'm going to add your translate.
