### ISSUE TITLE
Plugin Not Work

### ISSUE THREAD

**Issue by techclassin** [iazami/IMDBi#8]
Loading ...
 Loading ...
Loading ...
But No Data Show

**Comment by iazami** [comment]
quote from OMDB API (the source that i used in this plugin to receive information)

> 02/04/17 - Error 503/The service is unavailable! I KNOW! I've been working throughout the night trying to track down the bot/script/attack causing this issue, it's not normal activity as someone decided it was a good idea to open over 50+ concurrent connections and spam 300+ million requests an hour. Unfortunately the majority of features available to me to prevent these sorts of attacks are browser security checks (which are currently enabled so you can read this message) this is only temporary as I'm aware it breaks the majority of API implementations. Sorry for the inconvenience and I'll be working nonstop to get this resolved ASAP.
>
so, basically this is out of my control
